services:
  postgres:
    image: postgres:16
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_DB: messenger_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
  
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRES_DB: messenger_db
          POSTGRES_USER: root
          POSTGRES_PASSWORD: mypassword
          POSTGRES_SYNC: true
    depends_on:
      - postgres
    command: sh -c "npm install && npm run start:dev"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
      - "24678:24678"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  pg_data:
