services:
  postgres:
    image: postgres:16
    container_name: messenger_db
    restart: always
    environment:
      POSTGRES_DB: messenger_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data: