version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: maiven_messenger_db
    restart: always
    environment:
      # Move to .env
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: maiven_messenger_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: